# -*- coding: utf-8 -*-
"""pulsar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w46OtDIiy5YG7IcgAOrTIKPwoRkQCx5Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.utils import plot_model

import keras_tuner as kt
from tensorflow.keras.optimizers import Adam

df = pd.read_csv('cleaned_pulsar_data.csv')

df.info()

df.head()

X = df.drop(columns=['target_class'])
y = df['target_class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

simple_model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(1, activation='sigmoid')
])
simple_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

complex_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])
complex_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

def build_model(hp):
    model = Sequential()

    # input
    model.add(Dense(
        units=hp.Int('input_units', min_value=16, max_value=128, step=16),
        activation=hp.Choice('input_activation', ['relu', 'tanh']),
        input_shape=(X.shape[1],)
    ))

    # middle
    for i in range(hp.Int('num_hidden_layers', 1, 3)):
        model.add(Dense(
            units=hp.Int(f'hidden_units_{i}', min_value=16, max_value=128, step=16),
            activation=hp.Choice(f'activation_{i}', ['relu', 'tanh'])
        ))
        model.add(Dropout(hp.Float(f'dropout_{i}', 0.0, 0.5, step=0.1)))

    # output
    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer=Adam(hp.Float('learning_rate', 1e-4, 1e-2, sampling='log')),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    executions_per_trial=1,
    directory='my_dir',
    project_name='pulsar_net'
)

tuner.search(X_train, y_train, validation_split=0.2, epochs=30)

best_model = tuner.get_best_models(1)[0]

history_simple = simple_model.fit(X_train, y_train, validation_split=0.2, epochs=30, verbose=0)

history_complex = complex_model.fit(X_train, y_train, validation_split=0.2, epochs=30, verbose=0)

history_best = best_model.fit(X_train, y_train, validation_split=0.2, epochs=30, verbose=0)

import matplotlib.pyplot as plt

plt.plot(history_simple.history['accuracy'], label='Simple Model')
plt.plot(history_complex.history['accuracy'], label='complexed Model')
plt.plot(history_best.history['accuracy'], label='Tuned Model')
plt.title('Training Accuracy Comparison')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()



# train two models
history_simple = simple_model.fit(X_train, y_train, epochs=30, batch_size=32, validation_split=0.2, verbose=0)
history_complex = complex_model.fit(X_train, y_train, epochs=30, batch_size=32, validation_split=0.2, verbose=0)

# model predication & evaluation
y_pred_simple = (simple_model.predict(X_test) > 0.5).astype("int32")
y_pred_complex = (complex_model.predict(X_test) > 0.5).astype("int32")

report_simple = classification_report(y_test, y_pred_simple, output_dict=True)
report_complex = classification_report(y_test, y_pred_complex, output_dict=True)

best_model.save("best_pulsar_model.h5")

report_simple

report_complex

plot_model(model=simple_model, show_shapes=True, show_layer_names=True, to_file='simple_model.png')

plot_model(model=complex_model, show_shapes=True, show_layer_names=True, to_file='complex_model.png')